name: Publish
on:
  push:
    branches: [main]

jobs:
  deployment:
    timeout-minutes: 60
    name: "deploy to github"
    runs-on: ubuntu-latest
    steps:
      - name: deploy to github page
        run: npm run deploy
