name: Publish
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deployment:
    timeout-minutes: 60
    name: "deploy to github"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Set output variables
        id: vars
        run: |
          github_token=${{ secrets.GITHUB_TOKEN }}
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          check-name: 'tests'
          repo-token: ${{ steps.vars.outputs.github_token }}
          wait-interval: 10
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ steps.vars.outputs.github_token }}
          publish_dir: build
