name: publish-pages-build-deployment
on:
  push:
    branches: [main]
  pull_request:
    types:
      - closed

jobs:
  deployment:
    timeout-minutes: 60
    if: github.event.pull_request.merged == true
    needs: [tests]
    name: "deploy to github"
    runs-on: ubuntu-latest
    steps:
      - name: deploy to github page
        run: npm run deploy
